const subCategorias = [
  "- Seleccione -",
  "Comercio - Agricultura",
  "Comercio - Energia y Mineria",
  "Comercio - Textiles",
  "Comercio - Ganadería",
  "Comercio - Negocios y Finanzas",
  "Comercio - Aeroespacial",
  "Comercio - Tecnología",
  "Comercio - Cámara de Comercio",
  "Academia - Ingenieria",
  "Academia - Publicidad",
  "Academia - Administracion",
  "Academia - Humanidades",
  "Academia - Arquitectura",
  "Academia - Leyes",
  "Academia - Medicina",
  "Academia - General",
  "Gobierno - Gobernacion",
  "Gobierno - Alcaldía",
  "Gobierno - Otro",
  "Gobierno - Agencia Nacional Mineria",
  "Turismo",
];

export default subCategorias;
